### ISSUE TITLE
CommonsBooking erzeugt fatal error bei WPBakery

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1030]
```
Ein Fehler vom Typ E_ERROR wurde in der Zeile 242 der Datei /var/www/web118/html/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/CustomPostType.php verursacht. Fehlermeldung: Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, array given in /var/www/web118/html/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/CustomPostType.php:242
Stack trace:
#0 /var/www/web118/html/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/CustomPostType.php(242): strpos()
#1 /var/www/web118/html/wp-includes/class-wp-hook.php(307): CommonsBooking\Wordpress\CustomPostType\CustomPostType->CommonsBooking\Wordpress\CustomPostType\{closure}()
#2 /var/www/web118/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#3 /var/www/web118/html/wp-includes/plugin.php(522): WP_Hook->do_action()
#4 /var/www/web118/html/wp-includes/class-wp-query.php(1804): do_action_ref_array()
#5 /var/www/web118/html/wp-includes/class-wp-query.php(3542): WP_Query->get_posts()
#6 /var/www/web118/html/wp-includes/post.php(2430): WP_Query->query()
#7 /var/www/web118/html/wp-content/plugins/js_composer/include/autoload/class-vc-settings-presets.php(255): get_posts()
#8 /var/www/web118/html/wp-content/plugins/js_composer/include/autoload/class-vc-settings-presets.php(388): Vc_Settings_Preset::listSettingsPresets()
#9 /var/www/web118/html/wp-content/plugins/js_composer/include/autoload/vc-settings-presets.php(250): Vc_Settings_Preset::addVcPresetsToShortcodes()
#10 /var/www/web118/html/wp-includes/class-wp-hook.php(307): vc_add_new_elements_to_box()
#11 /var/www/web118/html/wp-includes/plugin.php(189): WP_Hook->apply_filters()
#12 /var/www/web118/html/wp-content/plugins/js_composer/include/classes/editors/popups/class-vc-add-element-box.php(80): apply_filters()
#13 /var/www/web118/html/wp-content/plugins/js_composer/include/classes/editors/popups/class-vc-add-element-box.php(94): Vc_Add_Element_Box->shortcodes()
#14 /var/www/web118/html/wp-content/plugins/js_composer/include/templates/editors/popups/vc_ui-panel-add-element.tpl.php(35): Vc_Add_Element_Box->getControls()
#15 /var/www/web118/html/wp-content/plugins/js_composer/include/helpers/helpers.php(978): require('...')
#16 /var/www/web118/html/wp-content/plugins/js_composer/include/classes/editors/popups/class-vc-add-element-box.php(130): vc_include_template()
#17 /var/www/web118/html/wp-content/plugins/js_composer/include/templates/editors/partials/backend_editor_footer.tpl.php(10): Vc_Add_Element_Box->render()
#18 /var/www/web118/html/wp-content/plugins/js_composer/include/helpers/helpers.php(978): require('...')
#19 /var/www/web118/html/wp-content/plugins/js_composer/include/classes/editors/class-vc-backend-editor.php(137): vc_include_template()
#20 /var/www/web118/html/wp-includes/class-wp-hook.php(307): Vc_Backend_Editor->renderEditorFooter()
#21 /var/www/web118/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#22 /var/www/web118/html/wp-includes/plugin.php(474): WP_Hook->do_action()
#23 /var/www/web118/html/wp-admin/admin-footer.php(78): do_action()
#24 /var/www/web118/html/wp-admin/post.php(369): require_once('...')
#25 {main}
thrown
```

Grund ist, dass an einem Punkt den ich leider nicht nachvollziehen kann der Wert $orderby eine Array ist:

![image](https://user-images.githubusercontent.com/6433480/166260992-d13c09ce-4c4a-4bcd-8c7b-293fe5b16ecd.png)

Konnte den Fehler auch mit der neusten Version von CommonsBooking und WPBakery nachbauen, scheint erst seit der 2.7 aufzutreten. 

Der absolut dreckigste aber leider auch funktionierende Hotfix liegt im branch hotfix/wp-bakery , ich komme da leider gerade nicht weiter.

@markus-mw @chriwen , könnt ihr euch das mal anschauen?

**Comment by hansmorb** [comment]
Gerade nochmal getestet mit frischer WP, CB 2.6.12  und WPBakery 6.9.2 Installation und der Fehler tritt trotzdem auf, hat also wahrscheinlich nichts mit dem letzten Update zu tun.

**Comment by chriwen** [comment]
@markus-mw Kannst du dir das mal anschauen, bitte?

**Comment by markus-mw** [comment]
@hansmorb , @chriwen : Ich hab das Plugin zwar nicht zur Hand aber versuchts bitte mal mit dem bugfix/issue-1030 nochmal.

**Comment by hansmorb** [comment]
Das sieht gut aus!
