### ISSUE TITLE
Fehlende Exceptionbehandlung

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1302]
Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 43 der Datei /var/www/vhosts/freie-raeder.org/httpdocs/freielasten/wp-content/plugins/commonsbooking/src/Repository/BookablePost.php verursacht. Fehlermeldung: Uncaught TypeError: CommonsBooking\Repository\BookablePost::getByCurrentUser(): Return value must be of type array, bool returned in /var/www/vhosts/freie-raeder.org/httpdocs/freielasten/wp-content/plugins/commonsbooking/src/Repository/BookablePost.php:43
Stack trace:
#0 /var/www/vhosts/freie-raeder.org/httpdocs/freielasten/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Booking.php(842): CommonsBooking\Repository\BookablePost::getByCurrentUser()
#1 /var/www/vhosts/freie-raeder.org/httpdocs/freielasten/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Booking.php(766): CommonsBooking\Wordpress\CustomPostType\Booking->getCustomFields()
#2 /var/www/vhosts/freie-raeder.org/httpdocs/freielasten/wp-includes/class-wp-hook.php(308): CommonsBooking\Wordpress\CustomPostType\Booking->registerMetabox()

Das sollte abgefangen werden.

**Comment by datengraben** [comment]
Ggf. kann es auch auftreten, wenn `WP_DEBUG` gesetzt ist. Aber so wie du es gelöst hast, ist es auf jeden Fall besser.
