### ISSUE TITLE
Error causes recovery mode in Wordpress backend

### ISSUE THREAD

**Issue by Beeblebrox21** [wielebenwir/commonsbooking#1324]
Ein Fehler vom Typ E_ERROR wurde in der Zeile 247 der Datei /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/CustomPostType.php verursacht. 

Fehlermeldung: 
```
Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, array given in /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/CustomPostType.php:247 Stack trace: #0 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/CustomPostType.php(247): strpos(Array, 'post_') 
#1 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-includes/class-wp-hook.php(310): CommonsBooking\Wordpress\CustomPostType\CustomPostType->CommonsBooking\Wordpress\CustomPostType\{closure}(Object(WP_Query)) 
#2 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array) 
#3 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-includes/plugin.php(565): WP_Hook->do_action(Array) 
#4 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-includes/class-wp-query.php(1881): do_action_ref_array('pre_get_posts', Array) 
#5 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-includes/class-wp-query.php(3800): WP_Query->get_posts() 
#6 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-includes/class-wp-query.php(3932): WP_Query->query(Array) 
#7 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-includes/post.php(6094): WP_Query->__construct(Array) 
#8 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-content/plugins/commonsbooking/src/Helper/Wordpress.php(19): get_pages() 
#9 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-content/plugins/commonsbooking/includes/OptionsArray.php(117): CommonsBooking\Helper\Wordpress::getPageListTitle() 
#10 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-content/plugins/commonsbooking/src/Plugin.php(453): include('/var/www/vhosts...') 
#11 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-includes/class-wp-hook.php(310): CommonsBooking\Plugin::registerAdminOptions('') 
#12 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array) 
#13 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
#14 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-settings.php(632): do_action('init') 
#15 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-config.php(97): require_once('/var/www/vhosts...') 
#16 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-load.php(50): require_once('/var/www/vhosts...') 
#17 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-admin/admin.php(34): require_once('/var/www/vhosts...') 
#18 /var/www/vhosts/hosting189402.ae81f.netcup.net/krafts-hof.de/httpdocs/wp-admin/index.php(10): require_once('/var/www/vhosts...') 
#19 {main} thrownA clear and concise description of what the bug is.
```

PHP 8.2, WP 6.3 deutsch

**Comment by hansmorb** [comment]
Danke, der Fehler ist bereits bekannt, #1309 . Wir arbeiten daran.

**Comment by datengraben** [comment]
duplicate #1309
