### ISSUE TITLE
REDIS Uncaught Exception

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1352]
Warning: Undefined array key "maxmemory_policy" in XXwp-content/plugins/commonsbooking/vendor/symfony/cache/Adapter/RedisTagAwareAdapter.php on line 320

Fatal error: Uncaught TypeError: Symfony\Component\Cache\Adapter\RedisTagAwareAdapter::getRedisEvictionPolicy(): Return value must be of type string, null returned in XXwp-content/plugins/commonsbooking/vendor/symfony/cache/Adapter/RedisTagAwareAdapter.php:320 Stack trace: #0 XXwp-content/plugins/commonsbooking/vendor/symfony/cache/Adapter/RedisTagAwareAdapter.php(94): Symfony\Component\Cache\Adapter\RedisTagAwareAdapter->getRedisEvictionPolicy() #1 XXwp-content/plugins/commonsbooking/vendor/symfony/cache/Adapter/AbstractTagAwareAdapter.php(190): Symfony\Component\Cache\Adapter\RedisTagAwareAdapter->doSave() #2 XXwp-content/plugins/commonsbooking/vendor/symfony/cache/Traits/AbstractAdapterTrait.php(276): Symfony\Component\Cache\Adapter\AbstractTagAwareAdapter->commit() #3 XXwp-content/plugins/commonsbooking/src/Service/Cache.php(174): Symfony\Component\Cache\Adapter\AbstractTagAwareAdapter->save() #4 XXwp-content/plugins/commonsbooking/src/Repository/BookablePost.php(110): CommonsBooking\Plugin::setCacheItem() #5 XXwp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Timeframe.php(475): CommonsBooking\Repository\BookablePost::getByCurrentUser() #6 XXwp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Timeframe.php(434): CommonsBooking\Wordpress\CustomPostType\Timeframe->getCustomFields() #7 XXwp-includes/class-wp-hook.php(310): CommonsBooking\Wordpress\CustomPostType\Timeframe->registerMetabox() #8 XXwp-includes/class-wp-hook.php(334): WP_Hook->apply_filters() #9 XXwp-includes/plugin.php(517): WP_Hook->do_action() #10 XXwp-content/plugins/commonsbooking/vendor/cmb2/cmb2/bootstrap.php(26): do_action() #11 XXwp-content/plugins/commonsbooking/vendor/cmb2/cmb2/init.php(165): cmb2_bootstrap() #12 XXwp-includes/class-wp-hook.php(310): CMB2_Bootstrap_2101->include_cmb() #13 XXwp-includes/class-wp-hook.php(334): WP_Hook->apply_filters() #14 XXwp-includes/plugin.php(517): WP_Hook->do_action() #15 XXwp-settings.php(632): do_action() #16 XXwp-config.php(67): require_once('...') #17 XXwp-load.php(50): require_once('...') #18 XXwp-admin/admin.php(34): require_once('...') #19 XXwp-admin/index.php(10): require_once('...') #20 {main} thrown in XXwp-content/plugins/commonsbooking/vendor/symfony/cache/Adapter/RedisTagAwareAdapter.php on line 320

**Comment by hansmorb** [comment]
Hmm, habe den TypeError übersehen. Scheint wohl ein REDIS oder Symfony Problem zu sein, da können wir nicht viel machen.
