### ISSUE TITLE
GBFS Schema kann nicht abgerufen werden

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1531]
/wp-json/commonsbooking/v1/gbfs.json/schema
wp-json/commonsbooking/v1/station_information.json/schema

Die Routen erzeugen einen Fatal Error:

Fatal error: Uncaught RuntimeException: Could not retrieve schema json from /var/www/vhosts/XXXXXX/wp-content/plugins/commonsbooking/includes/gbfs-json-schema/gbfs.json in /var/www/vhosts/XXXXXX/wp-content/plugins/commonsbooking/src/API/BaseRoute.php:140 Stack trace: #0 /var/www/vhosts/XXXXXX/wp-content/plugins/commonsbooking/src/API/BaseRoute.php(152): CommonsBooking\API\BaseRoute->getSchemaJson() #1 /var/www/vhosts/XXXXXX/wp-includes/rest-api/endpoints/class-wp-rest-controller.php(311): CommonsBooking\API\BaseRoute->add_additional_fields_schema(Array) #2 /var/www/vhosts/XXX/wp-includes/rest-api/endpoints/class-wp-rest-controller.php(323): WP_REST_Controller->get_item_schema() #3 /var/www/vhosts/XXX in /var/www/vhosts/XXXXXX/wp-content/plugins/commonsbooking/src/API/BaseRoute.php on line 140

**Comment by hansmorb** [comment]
Magst du dir das mal angucken?
Soweit ich das sehen kann ist dieser Commit 751b26a3902cf67f1690775eb9dd95eac32c991f vielleicht die Ursache. Das Problem ist, dass der Parameter missverständlicherweise "schemaUrl" heisst obwohl es ein lokaler Dateipfad ist. Dann ergibt die wp_remote_get() nicht mehr so viel Sinn.
